```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false



library(tidyverse)
library(plotly)
library(echarts4r)
library(quarto)
library(kableExtra)
library(apexcharter)


# 
dfag <- read.csv("data/AGD.csv", header = T)
dfat <- read.csv("data/ATD.csv", header = T)

dfag$Ano <- forcats::as_factor(dfag$Ano)
dfag$Meses <- forcats::as_factor(dfag$Meses)
dfag$Agendamentos <- forcats::as_factor(dfag$Agendamentos)
dfat$Ano <- forcats::as_factor(dfat$Ano)
dfat$Meses <- forcats::as_factor(dfat$Meses)
dfat$Classificacao<- forcats::as_factor(dfat$Classificacao)
```

# Ano: 2022 | Período: Janeiro - Dezembro {.unnumbered}

## Agendamentos

::: panel-tabset
## Parte A

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false

dfag |> filter(
    Ano == 2022
  ) |> group_by(Ano) |> 
  summarise(Total = sum(Quantidade))|> 
  # mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |> 
   kbl(caption = "Tabela 1.1. Frequência absoluta: Agendamentos.",
      col.names = c("Ano", 
                    "Frequência Absoluta"),
        align = 'ccc',
        ) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
  column_spec(1, color = "black", bold = T, italic = T) |> 
  column_spec(2, color = "darkblue", bold = T) |> 
  # column_spec(3, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T) 
```

## Parte B

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false

dfag |> filter(
  Ano == 2022
  ) |> group_by(Ano, Agendamentos) |> 
  summarise(Total = sum(Quantidade)) |> 
  mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |> 
  kbl(caption = "Tabela 1.2. Frequências absoluta e relativa: Classificações de Agendamento  <br><i>Valores agrupados por ano e classificações.</i>",
      col.names = c("Ano", 
                    "Classificações de Agendamento",
                    "Frequência Absoluta",
                    "Frequência relativa (em%)"),
        align = 'ccc',
        ) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
   column_spec(1, color = "black", bold = T, italic = T) |> 
   column_spec(2, color = "darkgray", bold = F, italic = T) |> 
  column_spec(3, color = "darkblue", bold = T) |> 
  column_spec(4, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T)
```

## Parte C

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false





dfag |> 
  filter(Ano == 2022) |> 
  group_by(Agendamentos) |>
  # mutate(Freq_Rel = round(Quantidade/sum(Quantidade)*100,1)  ) |> 
  apex(type = "column", 
       mapping = aes(x = Meses, 
                     y = Quantidade, 
                     fill = Agendamentos)) |> 
  ax_labs(
    title = "Gráfico 1.1. Freqências absolutas mensais - Classificações de Agendamentos",
    subtitle = ""
    )




```

## Parte D

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false


dfag |> filter(
  Ano == 2022
) |> group_by(Meses, Agendamentos) |> 
  summarise(Total = sum(Quantidade)) |> 
  mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |>
  select(-Total) |> 
  tidyr::pivot_wider(names_from = Agendamentos ,values_from = Freq_Rel) |> 
  kbl(caption = "Tabela 1.3. Frequências relativas (em %): Classificações de Agendamento  <br><i>Valores agrupados por mês e classificação.</i>",
    col.names = c("Meses", 	
                  "Atendimentos efetuados",	
                  "Atendimentos não efetuados"),
    align = 'ccc',
) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
  # column_spec(1, color = "black", bold = T, italic = T) |> 
  column_spec(1, color = "darkgray", bold = F, italic = T) |> 
  column_spec(2, color = "darkblue", bold = T) |> 
  column_spec(3, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T)


```

## Parte E

```{r}

#| echo: false
#| message: false
#| error: false
#| warning: false
dfag |> 
  filter(
    Ano == 2022
  ) |> group_by(Meses) |> 
  summarise(Total = sum(Quantidade)) |> 
  e_charts() |> 
  e_boxplot(Total, outliers = T, name = "Agendamentos (GERAL)") |> 
  e_tooltip(trigger = "axis",  valueFormatter = htmlwidgets::JS("
                                        (value) => '' + Number(value).toFixed(0)
                                        ")) |> 
  e_title(text = "Gráfico 1.2. Boxplot - Agendamentos")
```

## Parte F

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false


dfag |> 
  filter(
    Ano == 2022
  ) |> group_by(Agendamentos) |> 
  e_charts() |> 
  e_boxplot(Quantidade, outliers = T) |> 
  e_tooltip(trigger = "axis",  valueFormatter = htmlwidgets::JS("
                                        (value) => '' + Number(value).toFixed(0)
                                        ")) |> 
  e_title(text = "Gráfico 1.3. Boxplot - Classificações de Agendamento")
```
:::

> RESUMO:
>
> > No ano de 2022 a equipe teve **26 717 agendamentos**, dos quais ***91,4%*** (24 406) foram *efetivados* e ***8,6%*** (2 311) *cancelados*.
> >
> > A **mediana**\* de *agendamentos* é de **2 239**, de *atendimentos efetuados* é **2 005** e de *atendimentos não efetuados* é **198**.

::: {.unnumbered style="font-size: 13px; text-align:justify; background-color: #EAF0CE; padding: 15px 18px 12px 18px; border-radius: 10px 5% / 20px 25em 30px 35em;"}
:::

------------------------------------------------------------------------

## Atendimentos

:::: panel-tabset
## Parte A

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false

dfat |> filter(
    Ano == 2022
  ) |> group_by(Ano) |> 
  summarise(Total = sum(Quantidade))|> 
  # mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |> 
   kbl(caption = "Tabela 2.1. Frequência absoluta: Atendimentos - Total do período.",
      col.names = c("Ano", 
                    "Frequência Absoluta"),
        align = 'ccc',
        ) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
  column_spec(1, color = "black", bold = T, italic = T) |> 
  column_spec(2, color = "darkblue", bold = T) |> 
  # column_spec(3, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T) 
```

## Parte B

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false





dfat |> filter(
  Ano == 2022
) |> group_by(Classificacao) |> 
  summarise(Total = sum(Quantidade)) |> 
  mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |> 
  kbl(caption = "Tabela 2.2. Frequências absoluta e relativa: Classificações de Atendimento. <br><i>Valores agrupados por classificações conforme o total do período.</i>",
      col.names = c( 
                    "Classificações de Atendimento",
                    "Frequência Absoluta",
                    "Frequência relativa (em%)"),
        align = 'ccc',
        ) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
   # column_spec(1, color = "black", bold = T, italic = T) |> 
   column_spec(1, color = "darkgray", bold = F, italic = T) |> 
  column_spec(2, color = "darkblue", bold = T) |> 
  column_spec(3, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T)
```

## Parte C

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false


dfat |> group_by(Classificacao) |>
  filter(
    Ano == 2022
  ) |> 
  e_charts(Meses, timeline = T) |> 
  e_bar(Quantidade, symbol_size = 5,name = "Frequência:", itemStyle = list(
    borderColor = "darkgrey", borderWidth = '.7') ) |> 
  e_labels(position = 'insideTop',
            fontSize = 14, 
           fontStyle = 'bold') |> 
  e_legend(show = FALSE) |> 
  e_tooltip(trigger = "axis",
  valueFormatter = htmlwidgets::JS("
              (value) => '' + Number(value).toFixed(0)
                                        ")) |> 
  e_theme("essos") |> 
  e_timeline_opts(
    axis_type = "category",
    playInterval = 2055
  ) |> 
  e_title(text = "Gráfico 2.1. Frequência absoluta mensal.",
          subtext = "Classificações de atendimento.")

```

::: {.unnumbered style="font-size: 13px; text-align:center; background-color: #EAF0CE; padding: 15px 18px 12px 18px; border-radius: 15px 10% / 25px 30em 35px 40em;"}
Interconsulta \<\> Primeira Vez \<\> Quimioterapia \<\> Retorno
:::

## Parte D

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false

dfat |> filter(
  Ano == 2022
) |> group_by(Meses, Classificacao) |> 
  summarise(Total = sum(Quantidade)) |> 
  mutate(Freq_Rel = round( (Total/sum(Total)*100) ,1)) |>
  select(-Total) |> 
  tidyr::pivot_wider(names_from = Classificacao ,values_from = Freq_Rel) |> 
  kbl(caption = "Tabela 2.3. Frequências relativas mensais (em %): Classificações de Atendimento.  <br><i>Valores agrupados por mês e classificação.</i>",
      col.names = c("Meses", 	
                    "Interconsulta", 
                    "Primeira Vez", 
                    "Quimioterapia",
                    "Retorno"),
      align = 'ccccc',
  ) |> 
  kable_minimal(full_width = F, html_font = "Cambria", c("hover", "striped")) |> 
  # column_spec(1, color = "black", bold = T, italic = T) |> 
  column_spec(1, color = "darkgray", bold = F, italic = T) |> 
  column_spec(2, color = "darkred", bold = T) |> 
  column_spec(3, color = "darkred", bold = T) |> 
  column_spec(4, color = "darkred", bold = T) |> 
  column_spec(5, color = "darkred", bold = T) |> 
  footnote(general = "Tasy.",
           general_title = "Fonte: ", 
           number_title = "Type I: ",
           footnote_as_chunk = T)




```

## Parte E

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false


dfat |> 
  filter(
  Ano == 2022
  ) |> group_by(Classificacao) |> 
  e_charts() |> 
  e_boxplot(Quantidade, outliers = T) |> 
  e_tooltip(trigger = "axis",  valueFormatter = htmlwidgets::JS("
                                        (value) => '' + Number(value).toFixed(0)
                                        ")) |> 
  e_title(text = "Gráfico 2.2. Boxplot - Classificações de Atendimento") |> 
  e_theme("essos")

```
::::

> RESUMO:
>
> > Do total de atendimentos:
> >
> > -   Interconsulta = ***1,7%*** (416);
> >
> > -   Primeira Vez = ***9,7%*** (2 374);
> >
> > -   Quimioterapia = ***13,5%*** (3 283);
> >
> > -   Retorno = ***75,1%*** (18 333).
> >
> > A **mediana** de *atendimentos* de acordo com a classificação é:
> >
> > -   Interconsulta = **29**;
> >
> > -   Primeira Vez = **197**;
> >
> > -   Quimioterapia = **271**;
> >
> > -   Retorno = **1 525**.

------------------------------------------------------------------------
